
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import sun.audio.AudioData;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import sun.audio.ContinuousAudioDataStream;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author S-golden
 */
public class Eexpart extends javax.swing.JFrame {

    /**
     * Creates new form Eexpart
     */
    
   int score=0;
    Timer time;
    
         AudioPlayer MGP =AudioPlayer.player;
         AudioStream BGM,BGMend , BGMend2;
         AudioData MD,MDend, MDend2;
         ContinuousAudioDataStream loop=null;
         AudioPlayer MGP2 =AudioPlayer.player;
         AudioStream BGM2, BGM2end,BGM2end2;
         AudioData MD2, MD2end,MD2end2;
         ContinuousAudioDataStream loop2=null;
         
         ContinuousAudioDataStream loopend=null;
         ContinuousAudioDataStream loopend2=null;
         
         AudioPlayer MGPend =AudioPlayer.player;
         AudioPlayer MGPend2 =AudioPlayer.player;
         
    public Eexpart() {
        initComponents();
        jButton4.setEnabled(false);
         tf.setEnabled(false);
         btnreset.setEnabled(false);
         lbw.setVisible(false);
         lbl.setVisible(false);
         lba.setVisible(false);
         lbaa.setVisible(false);
         btnstart.setEnabled(false);
        
           ContinuousAudioDataStream loop=null;
        try{
            BGM2 = new AudioStream(new FileInputStream("C:\\Users\\S-golden\\Documents\\NetBeansProjects\\ABC123\\Stag2.wav"));
            MD2=BGM2.getData();
            loop2= new ContinuousAudioDataStream(MD2);
        }catch(Exception e){
            
        }
        MGP.stop(loop);
        
        MGP2.start(loop2); 
      // MGP2.stop(loop2);
    }

     public void gameSound(){
          InputStream in;
        
        try{
            in=new FileInputStream(new File("C:\\Users\\S-golden\\Documents\\NetBeansProjects\\ABC123\\Bigl.wav"));
            AudioStream  audios=new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch(Exception e){
            e.printStackTrace();
        }
    }
     public void gameSound2(){
          InputStream in;
        
        try{
            in=new FileInputStream(new File("C:\\Users\\S-golden\\Documents\\NetBeansProjects\\ABC123\\yes.wav"));
            AudioStream  audios=new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch(Exception e){
            e.printStackTrace();
        }
    }
     public void gameSound3(){
         
            ContinuousAudioDataStream loopp=null;
        try{
            BGM2end = new AudioStream(new FileInputStream("C:\\Users\\S-golden\\Documents\\NetBeansProjects\\ABC123\\congrat.wav"));
            MD2end=BGM2end.getData();
            loopend= new ContinuousAudioDataStream(MD2end);
        }catch(Exception e){
            
        }
        MGPend.stop(loopp);
        
        MGPend.start(loopend); 
    }
     public void gameSound4(){
         
            ContinuousAudioDataStream looppp=null;
        try{
            BGM2end2 = new AudioStream(new FileInputStream("C:\\Users\\S-golden\\Documents\\NetBeansProjects\\ABC123\\oh noo.wav"));
            MD2end2=BGM2end2.getData();
            loopend2= new ContinuousAudioDataStream(MD2end2);
        }catch(Exception e){
            
        }
        MGPend2.stop(looppp);
        
        MGPend2.start(loopend2); 
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lbw = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        lb6 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnstart = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        lb3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        lba = new javax.swing.JLabel();
        lbaa = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("EXPERT");

        lb5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 255, 255));
        lb5.setText("TOTAL SCORE :  0");

        lb4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 255, 255));
        lb4.setText("____");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lawal.jpg"))); // NOI18N

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lllll.jpg"))); // NOI18N

        lbw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wwww.jpg"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));

        lb2.setFont(new java.awt.Font("Tahoma", 1, 58)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("__");

        tf.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfKeyPressed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("ANSWER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        lb6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb6.setForeground(new java.awt.Color(255, 255, 255));
        lb6.setText("TIME :");

        lb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb.setForeground(new java.awt.Color(255, 255, 255));
        lb.setText("00:00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(tf, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lb6)
                        .addGap(18, 18, 18)
                        .addComponent(lb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb))
                .addGap(40, 40, 40))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btnstart.setBackground(new java.awt.Color(153, 153, 255));
        btnstart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnstart.setForeground(new java.awt.Color(51, 51, 0));
        btnstart.setText("START");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("How to Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(102, 102, 102));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnreset.setForeground(new java.awt.Color(51, 51, 0));
        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        lb3.setText("user");

        jRadioButton1.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("100 seconds");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("150 seconds");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("200 seconds");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lb3)
                        .addContainerGap())))
        );

        lba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anger.jpg"))); // NOI18N

        lbaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eureka 15.jpg"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbw, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lb4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lb5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbaa)
                        .addGap(18, 18, 18)
                        .addComponent(lba, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbaa)
                            .addComponent(lba, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbw, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb4)
                        .addGap(43, 43, 43))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String cl ="";
        String was =lb2.getText();;
        String g;
        g = String.format("%s", tf.getText());
        lb3.setText(g);

        if( tf.getText().contains("A" ) && lb2.getText().contains("1".toUpperCase()) ){
            gameSound2();
            score+=2;
            lb4.setText("Well Don!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("B" ) && lb2.getText().contains("2".toUpperCase())){
            gameSound2();
            score+=2;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("C" ) && lb2.getText().contains("3".toUpperCase())){
            gameSound2();
            score+=2;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("D" ) && lb2.getText().contains("4".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("E" ) && lb2.getText().contains("5".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("F" ) && lb2.getText().contains("6".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("G" ) && lb2.getText().contains("7".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("H" ) && lb2.getText().contains("8".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Correct!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("I" ) && lb2.getText().contains("9".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Correct!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("J" ) && lb2.getText().contains("10".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Correct!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("K" ) && lb2.getText().contains("11".toUpperCase())){
            gameSound2();
            score+=5;
            lb4.setText("I love your BRAIN!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("L" ) && lb2.getText().contains("12".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("I love your BRAIN!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("M" ) && lb2.getText().contains("13".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("I love your BRAIN!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("N" ) && lb2.getText().contains("14".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("I love your BRAIN!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("O" ) && lb2.getText().contains("15".toUpperCase())){
            gameSound2();
            score+=5;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("P" ) && lb2.getText().contains("16".toUpperCase())){
            gameSound2();
            score+=5;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("Q" ) && lb2.getText().contains("17".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("R" ) && lb2.getText().contains("18".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("S" ) && lb2.getText().contains("19".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("T" ) && lb2.getText().contains("20".toUpperCase())){
            gameSound2();
            score+=5;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("U" ) && lb2.getText().contains("21".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("V" ) && lb2.getText().contains("22".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("W" ) && lb2.getText().contains("23".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("X" ) && lb2.getText().contains("24".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("Y" ) && lb2.getText().contains("25".toUpperCase())){
            gameSound2();
            score+=2;
            lb4.setText("You are my Freind!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("Z" ) && lb2.getText().contains("26".toUpperCase())){
            gameSound2();
            score+=2;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else{
            gameSound();
            lbw.setVisible(false);
            lbl.setVisible(true);
            lb4.setText("HAHA!");
            tf.setText(cl);
        }
        String [] name = {"1","2","3","4","5","6","7","8","8","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26"};
        int round = (int)(Math.random()*name.length);

        lb2.setText(String.format("%s", name[round]));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // JOptionPane.showMessageDialog(null, "IDENTIFY THIS ALPHABET BY THER NUMBER\n example A to z  represent 1 to 26 in numbers \n and A=1. click OK to start  the Game", "HOW TO PLAY", WIDTH);
    }//GEN-LAST:event_jButton4KeyPressed

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
       String [] name = {"1","2","3","4","5","6","7","8","8","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26"};
        int round = (int)(Math.random()*name.length);

        lb2.setText(String.format("%s", name[round]));
        String was =lb2.getText();;
        String g;
        g = String.format("%s", tf.getText());
        lb3.setText(g);
        btnstart.setEnabled(false);
        btnreset.setEnabled(true);
        jButton4.setEnabled(true);
        tf.setEnabled(true);
        lba.setVisible(false);
        if(jRadioButton1.isSelected()){
            TimerClass tc = new TimerClass(101);
            time = new Timer(1000,tc);
            time.start();
        }else if(jRadioButton2.isSelected()){
            TimerClass tc = new TimerClass(151);
            time = new Timer(1000,tc);
            time.start();
        }else if(jRadioButton3.isSelected()){
            TimerClass tc = new TimerClass(201);
            time = new Timer(1000,tc);
            time.start();
        }else{

        }
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton3.setVisible(false);

    }//GEN-LAST:event_btnstartActionPerformed

     public class TimerClass implements ActionListener{
            int counter;
            
            public TimerClass(int counter){
                this.counter=counter;
            }
        public void actionPerformed(ActionEvent e){
            counter --;
             if(counter >=1){
                 lb.setText("" + counter);
             }else{
                 lb.setText("TIME OVER !" + counter);
                 time.stop();
                 MGP2.stop(loop2);
                 jButton4.setEnabled(false);
                 tf.setEnabled(false);
                 btnreset.setEnabled(true);
                 lbw.setVisible(false);
                 lbl.setVisible(false);
                 btnstart.setEnabled(false);
                 lba.setVisible(true);
                 if(score <= 49){
                     gameSound4();
                     lba.setVisible(true);
                     lbaa.setVisible(false);
                 }else if(score >= 50){
                     gameSound3();
                    lbaa.setVisible(true);
                    lba.setVisible(false);
                 }
             }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ContinuousAudioDataStream loop=null;
        try{
            BGM2 = new AudioStream(new FileInputStream("C:\\Users\\S-golden\\Documents\\NetBeansProjects\\ABC123\\how to play.wav"));
            MD2=BGM2.getData();
            loop2= new ContinuousAudioDataStream(MD2);
        }catch(Exception e){

        }
        MGP.stop(loop);

        MGP2.start(loop2);
        JOptionPane.showMessageDialog(null, "IDENTIFY THIS ALPHABET BY THER NUMBER\n example A to z  represent 1 to 26 in numbers \n and A=1. click OK to start  the Game", "HOW TO PLAY", WIDTH);
        MGP2.stop(loop2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        btnstart.setEnabled(true);
        btnreset.setEnabled(false);
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        jRadioButton3.setVisible(true);
        time.stop();
        MGPend.stop(loopend);
        MGPend2.stop(loopend2);

        score=0;
        lb5.setText("Total Score : ");
    }//GEN-LAST:event_btnresetActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        btnstart.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jRadioButton3.setSelected(false);
        btnstart.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(false);
        btnstart.setEnabled(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed
        public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
       
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MGP2.stop(loop2);
        close();
        Goldenkidis g = new Goldenkidis();
        g.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             String cl ="";
        String was =lb2.getText();;
        String g;
        g = String.format("%s", tf.getText());
        lb3.setText(g);

        if( tf.getText().contains("A" ) && lb2.getText().contains("1".toUpperCase()) ){
            gameSound2();
            score+=2;
            lb4.setText("Well Don!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("B" ) && lb2.getText().contains("2".toUpperCase())){
            gameSound2();
            score+=2;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("C" ) && lb2.getText().contains("3".toUpperCase())){
            gameSound2();
            score+=2;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("D" ) && lb2.getText().contains("4".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("E" ) && lb2.getText().contains("5".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("F" ) && lb2.getText().contains("6".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("G" ) && lb2.getText().contains("7".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Yes!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("H" ) && lb2.getText().contains("8".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Correct!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("I" ) && lb2.getText().contains("9".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Correct!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("J" ) && lb2.getText().contains("10".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Correct!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("K" ) && lb2.getText().contains("11".toUpperCase())){
            gameSound2();
            score+=5;
            lb4.setText("I love your BRAIN!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("L" ) && lb2.getText().contains("12".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("I love your BRAIN!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("M" ) && lb2.getText().contains("13".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("I love your BRAIN!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("N" ) && lb2.getText().contains("14".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("I love your BRAIN!!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("O" ) && lb2.getText().contains("15".toUpperCase())){
            gameSound2();
            score+=5;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("P" ) && lb2.getText().contains("16".toUpperCase())){
            gameSound2();
            score+=5;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("Q" ) && lb2.getText().contains("17".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("R" ) && lb2.getText().contains("18".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("S" ) && lb2.getText().contains("19".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("T" ) && lb2.getText().contains("20".toUpperCase())){
            gameSound2();
            score+=5;
            lb4.setText("You are the BEST!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("U" ) && lb2.getText().contains("21".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("V" ) && lb2.getText().contains("22".toUpperCase())){
            gameSound2();
            score+=4;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("W" ) && lb2.getText().contains("23".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("X" ) && lb2.getText().contains("24".toUpperCase())){
            gameSound2();
            score+=3;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("Y" ) && lb2.getText().contains("25".toUpperCase())){
            gameSound2();
            score+=2;
            lb4.setText("You are my Freind!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else if(tf.getText().contains("Z" ) && lb2.getText().contains("26".toUpperCase())){
            gameSound2();
            score+=2;
            lb4.setText("Good One!");
            lbw.setVisible(true);
            lbl.setVisible(false);
            lb5.setText("Total Score : " +score);
            tf.setText(cl);
        }else{
            gameSound();
            lbw.setVisible(false);
            lbl.setVisible(true);
            lb4.setText("HAHA!");
            tf.setText(cl);
        }
        String [] name = {"1","2","3","4","5","6","7","8","8","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26"};
        int round = (int)(Math.random()*name.length);

        lb2.setText(String.format("%s", name[round]));
        }
    }//GEN-LAST:event_tfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eexpart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eexpart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eexpart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eexpart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eexpart().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnstart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lba;
    private javax.swing.JLabel lbaa;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbw;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
